/**/helm_manager:
  ros__parameters:
    output_type: twist
    max_speed: 2.0
    max_yaw_speed: 0.5

/**/platform_sender:
  ros__parameters:
    width: 0.9
    length: 2.4
    reference_x: 0.0
    reference_y: 0.0
    color:
      red: 1.0
      green: 0.85
      blue: 0.0

    nav:
      source_names:
        - mru
      sources:
        mru:
          topics:
            orientation: "mavros/imu/data"
            position: "mavros/global_position/raw/fix"
            velocity: "mavros/global_position/raw/gps_vel"

/**/deltat:
  ros__parameters:
    frame_id: bizzy/deltat

/**/cube_bathymetry:
  ros__parameters:
    map_frame: bizzy/map
    cell_size: 0.5

/**/mru_transform:
  ros__parameters:
    sensors:
      mru:
        topics:
          orientation: "mavros/imu/data"
          position: "mavros/global_position/raw/fix"
          velocity: "mavros/global_position/raw/gps_vel"
    sensor_names:
    - mru

/**/udp_bridge:
  ros__parameters:
    name: bizzy
    port: 4200
    maximum_packet_size: 1000
    remotes_list:
      - operator
    remotes:
      operator:
        connections_list:
          - wifi
          - vpn
        connections:
          wifi:
            maximum_bytes_per_second: 1500000
            topics_list:
            - battery
            - command_response
            - deltat
            - deltat_grid
            - diagnostics
            - heartbeat
            - heartbeat_nav
            - hover_viz
            - local_costmap
            - local_costmap_footprint
            - global_costmap
            - oak_forward
            - oak_forward_info
            - oak_forward_raw
            - oak_segmentation_forward
            - oak_segmentation_forward_info
            - oak_segmentation_forward_raw
            - oak_starboard
            - oak_starboard_info
            - oak_starboard_raw
            - oak_segmentation_starboard
            - oak_segmentation_starboard_info
            - oak_segmentation_starboard_raw
            - oak_aft
            - oak_aft_info
            - oak_aft_raw
            - oak_segmentation_aft
            - oak_segmentation_aft_info
            - oak_segmentation_aft_raw
            - oak_port
            - oak_port_info
            - oak_port_raw
            - oak_segmentation_port
            - oak_segmentation_port_info
            - oak_segmentation_port_raw
            - odom
            - path_follower_visualization
            - plan
            - platforms
            - mavros_gps_status
            - mavros_position
            - mavros_orientation
            - mavros_velocity
            - tf
            - tf_static
            - usb_camera
            - usb_camera_info
            topics:
              command_response: {source: marine/response}
              diagnostics: {source: /diagnostics}
              global_costmap: {source: global_costmap/costmap, period: 3.0}
              heartbeat: {source: marine/heartbeat}
              heartbeat_nav: {source: marine/status/mission_manager}
              hover_viz: {source: hover_visualization}
              local_costmap: {source: local_costmap/costmap, period: 3.0}
              local_costmap_footprint: {source: local_costmap/published_footprint}
              odom: {source: odom}
              oak_forward:      {source: sensors/cameras/oak_forward/image_raw/compressed, period: 1.0}
              oak_forward_info: {source: sensors/cameras/oak_forward/camera_info}
              oak_forward_raw:    {source: sensors/cameras/oak_forward/image_raw, period: -1.0}
              oak_segmentation_forward:      {source: sensors/cameras/oak_forward/segmentation/compressed, period: 0.5}
              oak_segmentation_forward_info: {source: sensors/cameras/oak_forward/segmentation/camera_info}
              oak_segmentation_forward_raw:    {source: sensors/cameras/oak_forward/segmentation, period: -1.0}
              oak_starboard:      {source: sensors/cameras/oak_starboard/image_raw/compressed, period: 1.0}
              oak_starboard_info: {source: sensors/cameras/oak_starboard/camera_info}
              oak_starboard_raw:  {source: sensors/cameras/oak_starboard/image_raw, period: -1.0}
              oak_segmentation_starboard:      {source: sensors/cameras/oak_starboard/segmentation/compressed, period: 0.5}
              oak_segmentation_starboard_info: {source: sensors/cameras/oak_starboard/segmentation/camera_info}
              oak_segmentation_starboard_raw:    {source: sensors/cameras/oak_starboard/segmentation, period: -1.0}
              oak_aft:      {source: sensors/cameras/oak_aft/image_raw/compressed, period: 2.0}
              oak_aft_info: {source: sensors/cameras/oak_aft/camera_info}
              oak_aft_raw:  {source: sensors/cameras/oak_aft/image_raw, period: -1.0}
              oak_segmentation_aft:      {source: sensors/cameras/oak_aft/segmentation/compressed, period: 0.5}
              oak_segmentation_aft_info: {source: sensors/cameras/oak_aft/segmentation/camera_info}
              oak_segmentation_aft_raw:    {source: sensors/cameras/oak_aft/segmentation, period: -1.0}
              oak_port:      {source: sensors/cameras/oak_port/image_raw/compressed, period: 1.0}
              oak_port_info: {source: sensors/cameras/oak_port/camera_info}
              oak_port_raw:  {source: sensors/cameras/oak_port/image_raw, period: -1.0}
              oak_segmentation_port:      {source: sensors/cameras/oak_port/segmentation/compressed, period: 0.5}
              oak_segmentation_port_info: {source: sensors/cameras/oak_port/segmentation/camera_info}
              oak_segmentation_port_raw:    {source: sensors/cameras/oak_port/segmentation, period: -1.0}
              path_follower_visualization: {source: path_follower_visualization}
              deltat: {source: sensors/deltat/soundings}
              deltat_grid: {source: sensors/deltat/grid}
              battery: {source: /bizzy/mavros/battery}
              plan: {source: plan}
              platforms: {source: /marine/platforms}
              mavros_gps_status: {source: mavros/gpsstatus/gps1/raw}
              mavros_orientation: {source: mavros/imu/data}
              mavros_position: {source: mavros/global_position/raw/fix}
              mavros_velocity: {source: mavros/global_position/raw/gps_vel}
              tf: {source: /tf, queue_size: 25}
              tf_static: {source: /tf_static}
              usb_camera: {source: sensors/cameras/usb/image_raw/compressed}
              usb_camera_info: {source: sensors/cameras/usb/camera_info}

          vpn:
            maximum_bytes_per_second: 1000000
            topics_list:
            - battery
            - command_response
            - diagnostics
            - heartbeat
            - heartbeat_nav
            - hover_viz
            - oak_forward
            - oak_forward_info
            - oak_forward_raw
            - oak_segmentation_forward
            - oak_segmentation_forward_info
            - oak_segmentation_forward_raw
            # - oak_starboard
            # - oak_starboard_info
            # - oak_starboard_raw
            # - oak_segmentation_starboard
            # - oak_segmentation_starboard_info
            # - oak_segmentation_starboard_raw
            # - oak_aft
            # - oak_aft_info
            # - oak_aft_raw
            # - oak_segmentation_aft
            # - oak_segmentation_aft_info
            # - oak_segmentation_aft_raw
            # - oak_port
            # - oak_port_info
            # - oak_port_raw
            # - oak_segmentation_port
            # - oak_segmentation_port_info
            # - oak_segmentation_port_raw
            - odom
            - plan
            - platforms
            - mavros_gps_status
            - mavros_position
            - mavros_orientation
            - mavros_velocity
            - tf
            - tf_static
            topics:
              command_response: {source: marine/response}
              diagnostics: {source: /diagnostics}
              heartbeat: {source: marine/heartbeat}
              heartbeat_nav: {source: marine/status/mission_manager}
              hover_viz: {source: hover_visualization}
              odom: {source: odom}
              oak_forward:      {source: sensors/cameras/oak_forward/image_raw/compressed, period: 1.0}
              oak_forward_info: {source: sensors/cameras/oak_forward/camera_info}
              oak_forward_raw:    {source: sensors/cameras/oak_forward/image_raw, period: -1.0}
              oak_segmentation_forward:      {source: sensors/cameras/oak_forward/segmentation/compressed, period: 0.5}
              oak_segmentation_forward_info: {source: sensors/cameras/oak_forward/segmentation/camera_info}
              oak_segmentation_forward_raw:    {source: sensors/cameras/oak_forward/segmentation, period: -1.0}
              oak_starboard:      {source: sensors/cameras/oak_starboard/image_raw/compressed, period: 1.0}
              oak_starboard_info: {source: sensors/cameras/oak_starboard/camera_info}
              oak_starboard_raw:  {source: sensors/cameras/oak_starboard/image_raw, period: -1.0}
              oak_segmentation_starboard:      {source: sensors/cameras/oak_starboard/segmentation/compressed, period: 0.5}
              oak_segmentation_starboard_info: {source: sensors/cameras/oak_starboard/segmentation/camera_info}
              oak_segmentation_starboard_raw:    {source: sensors/cameras/oak_starboard/segmentation, period: -1.0}
              oak_aft:      {source: sensors/cameras/oak_aft/image_raw/compressed, period: 2.0}
              oak_aft_info: {source: sensors/cameras/oak_aft/camera_info}
              oak_aft_raw:  {source: sensors/cameras/oak_aft/image_raw, period: -1.0}
              oak_segmentation_aft:      {source: sensors/cameras/oak_aft/segmentation/compressed, period: 0.5}
              oak_segmentation_aft_info: {source: sensors/cameras/oak_aft/segmentation/camera_info}
              oak_segmentation_aft_raw:    {source: sensors/cameras/oak_aft/segmentation, period: -1.0}
              oak_port:      {source: sensors/cameras/oak_port/image_raw/compressed, period: 1.0}
              oak_port_info: {source: sensors/cameras/oak_port/camera_info}
              oak_port_raw:  {source: sensors/cameras/oak_port/image_raw, period: -1.0}
              oak_segmentation_port:      {source: sensors/cameras/oak_port/segmentation/compressed, period: 0.5}
              oak_segmentation_port_info: {source: sensors/cameras/oak_port/segmentation/camera_info}
              oak_segmentation_port_raw:    {source: sensors/cameras/oak_port/segmentation, period: -1.0}
              battery: {source: /bizzy/mavros/battery}
              plan: {source: plan}
              platforms: {source: /marine/platforms}
              mavros_gps_status: {source: mavros/gpsstatus/gps1/raw}
              mavros_orientation: {source: mavros/imu/data}
              mavros_position: {source: mavros/global_position/raw/fix}
              mavros_velocity: {source: mavros/global_position/raw/gps_vel}
              tf: {source: /tf}
              tf_static: {source: /tf_static}

/**/logger:
  ros__parameters:
    record:
      all_topics: false
      topics:
      - /diagnostics
      - /bizzy/mavros/battery
      - /bizzy/mavros/global_position/raw/fix
      - /bizzy/mavros/global_position/raw/gps_vel
      - /bizzy/mavros/gpsstatus/gps1/raw
      - /bizzy/mavros/imu/data
      - /bizzy/mavros/state
      - /bizzy/odom
      - /bizzy/marine/heartbeat
      - /bizzy/marine/status/mission_manager
      - /bizzy/robot_description
      - /bizzy/sensors/cameras/oak_forward/rgb/camera_info
      - /bizzy/sensors/cameras/oak_forward/rgb/image_raw/compressed
      - /bizzy/sensors/cameras/oak_starboard/rgb/camera_info
      - /bizzy/sensors/cameras/oak_starboard/rgb/image_raw/compressed
      - /bizzy/sensors/cameras/oak_aft/rgb/camera_info
      - /bizzy/sensors/cameras/oak_aft/rgb/image_raw/compressed
      - /bizzy/sensors/cameras/oak_port/rgb/camera_info
      - /bizzy/sensors/cameras/oak_port/rgb/image_raw/compressed
      - /bizzy/udp_bridge/bridge_info
      - /bizzy/udp_bridge/topic_statistics
      - /marine/platforms
      - /rosout
      - /tf
      - /tf_static
    storage:
      uri: /home/field/data/logs/bizzyboat
      max_bagfile_duration: 300
      storage_preset_profile: zstd_fast

/**/sonar_logger:
  ros__parameters:
    record:
      all_topics: false
      topics:
      - /diagnostics
      - /bizzy/odom
      - /bizzy/robot_description
      - /bizzy/sensors/deltat/soundings
      - /tf
      - /tf_static
    storage:
      uri: /home/field/project11/data/bizzyboat_sonar
      max_bagfile_duration: 300
      storage_preset_profile: zstd_fast
