/**/udp_bridge:
  ros__parameters:
    name: operator
    maximum_packet_size: 1000
    remotes_list:
      - bizzy
    remotes:
      bizzy:
        connections_list:
          - wifi
          - vpn
        connections:
          wifi:
            host: gabby_bb
            port: 4200
            return_host: salmon_bb
            return_port: 4200
            topics_list:
            - command
            - joystick_helm
            topics:
              command: {source: /bizzy/project11/command}
              joystick_helm: {source: /bizzy/piloting_mode/manual/helm}

          vpn:
            host: gabby_v
            port: 4200
            return_host: salmon_bv
            return_port: 4200
            topics_list:
            - command
            - joystick_helm
            topics:
              command: {source: /bizzy/project11/command}
              joystick_helm: {source: /bizzy/piloting_mode/manual/helm}
