teltonika_monitor:
  ros__parameters:
    host: 'router.bizzy'
    username: 'ros_monitor'
    password: 'ROS2_monitor'
    port: 443
    use_ssl: true
    poll_interval: 5.0
    hardware_id: 'router.bizzy'
    ignored_interfaces: ['mob1s2a1', 'wan1']
