teltonika_monitor:
  ros__parameters:
    host: 'router.op'
    username: 'ros_monitor'
    password: 'ROS2_monitor'
    port: 443
    use_ssl: true
    poll_interval: 5.0
    hardware_id: 'router.op'
    ignored_interfaces: ['mob1s1a1', 'mob1s2a1', 'wifi_bridge', 'mobile_lab']
