/**/platform_sender:
  ros__parameters:
    width: 0.8
    length: 1.75
    reference_x: -.225
    reference_y: 0.05
    color:
      red: 1.0
      green: 1.0
      blue: 0.0

    nav:
      source_names:
        - mru
        - posmv
      sources:
        mru:
          topics:
            orientation: "mavros/imu/data"
            position: "mavros/global_position/raw/fix"
            velocity: "mavros/global_position/raw/gps_vel"
        posmv:
          topics:
            orientation: "sensors/posmv/orientation"
            position: "sensors/posmv/position"
            velocity: "sensors/posmv/orientation"

/**/deltat:
  ros__parameters:
    frame_id: izzy/deltat

/**/cube_bathymetry:
  ros__parameters:
    map_frame: izzy/map
    cell_size: 0.5



/**/udp_bridge:
  ros__parameters:
    name: izzy
    port: 4200
    maximum_packet_size: 1000
    remotes_list:
      - operator
    remotes:
      operator:
        connections_list:
          - wifi
          - vpn
        connections:
          wifi:
            maximum_bytes_per_second: 500000
            topics_list:
            - battery
            - command_response
            - deltat
            - deltat_octomap
            - deltat_grid
            - diagnostics
            - heartbeat
            - heartbeat_nav
            - hover_viz
            - local_costmap
            - local_costmap_footprint
            - oak_rgb
            - oak_rgb_info
            - oak_segmentation
            - oak_segmentation_raw
            - oak_segmentation_info
            - oak_jolo_detections
            - odom
            - plan
            - platforms
            - posmv_position
            - posmv_orientation
            - posmv_velocity
            - mavros_gps_status
            - mavros_position
            - mavros_orientation
            - mavros_velocity
            - tf
            - tf_static
            topics:
              command_response: {source: project11/response}
              diagnostics: {source: /diagnostics}
              heartbeat: {source: project11/heartbeat} 
              heartbeat_nav: {source: project11/status/mission_manager} 
              hover_viz: {source: hover_visualization}
              local_costmap: {source: local_costmap/costmap, period: 3.0}
              local_costmap_footprint: {source: local_costmap/published_footprint}
              odom: {source: odom}
              oak_rgb: {source: sensors/cameras/front/oak/detections/passthrough/image_raw/throttled/compressed}
              oak_rgb_info: {source: sensors/cameras/front/oak/detections/passthrough/camera_info}
              oak_segmentation: {source: sensors/cameras/front/oak/segmentation/compressed}
              oak_segmentation_raw: {source: sensors/cameras/front/oak/segmentation, period: -1.0}
              oak_segmentation_info: {source: sensors/cameras/front/oak/segmentation/camera_info}
              oak_jolo_detections: {source: sensors/cameras/front/oak/detections/image_raw/compressed, period: 1.0}
              odom: {source: odom}
              deltat: {source: sensors/deltat/soundings}
              deltat_grid: {source: sensors/deltat/grid}
              deltat_octomap: {source: /izzy/sensors/deltat/occupied_cells_vis_array, period: 2.0}
              battery: {source: /izzy/mavros/battery}
              control_cmd_vel: {source: /izzy/project11/control/cmd_vel}
              plan: {source: plan}
              platforms: {source: /project11/platforms}
              posmv_position: {source: sensors/posmv/position, period: 0.1}
              posmv_orientation: {source: sensors/posmv/orientation, perioid: 0.1}
              posmv_velocity: {source: sensors/posmv/velocity, period: 0.1}
              mavros_gps_status: {source: mavros/gpsstatus/gps1/raw}
              mavros_orientation: {source: mavros/imu/data}
              mavros_position: {source: mavros/global_position/raw/fix}
              mavros_velocity: {source: mavros/global_position/raw/gps_vel}
              tf: {source: /tf}
              tf_static: {source: /tf_static}
              usb_camera: {source: sensors/cameras/front/usb/image_raw/compressed, period: 2.0}
              usb_camera_info: {source: sensors/cameras/front/usb/camera_info}

          vpn:
            maximum_bytes_per_second: 1000000
            topics_list:
            - battery
            - command_response
            - diagnostics
            - heartbeat
            - heartbeat_nav
            - hover_viz
            - oak_jolo_detections
            - odom
            - plan
            - platforms
            - posmv_position
            - posmv_orientation
            - posmv_velocity
            - mavros_gps_status
            - mavros_position
            - mavros_orientation
            - mavros_velocity
            - tf
            - tf_static
            - usb_camera
            - usb_camera_info
            topics:
              command_response: {source: project11/response}
              diagnostics: {source: /diagnostics}
              heartbeat: {source: project11/heartbeat} 
              heartbeat_nav: {source: project11/status/mission_manager} 
              hover_viz: {source: hover_visualization}
              odom: {source: odom}
              battery: {source: /izzy/mavros/battery}
              control_cmd_vel: {source: /izzy/project11/control/cmd_vel}
              oak_jolo_detections: {source: sensors/cameras/front/oak/detections/image_raw/compressed}
              plan: {source: plan}
              platforms: {source: /project11/platforms}
              posmv_position: {source: sensors/posmv/position, period: 0.1}
              posmv_orientation: {source: sensors/posmv/orientation, perioid: 0.1}
              posmv_velocity: {source: sensors/posmv/velocity, period: 0.1}
              mavros_gps_status: {source: mavros/gpsstatus/gps1/raw}
              mavros_orientation: {source: mavros/imu/data}
              mavros_position: {source: mavros/global_position/raw/fix}
              mavros_velocity: {source: mavros/global_position/raw/gps_vel}
              tf: {source: /tf}
              tf_static: {source: /tf_static}
              usb_camera: {source: sensors/cameras/front/usb/image_raw/compressed, period: 1.0}
              usb_camera_info: {source: sensors/cameras/front/usb/camera_info}



/**/logger:
  ros__parameters:
    record:
      all_topics: false
      comptession_format: zstd
      topics:
      - /diagnostics
      - /izzy/mavros/battery
      - /izzy/mavros/global_position/raw/fix
      - /izzy/mavros/global_position/raw/gps_vel
      - /izzy/mavros/gpsstatus/gps1/raw
      - /izzy/mavros/imu/data
      - /izzy/mavros/state
      - /izzy/odom
      - /izzy/project11/heartbeat
      - /izzy/project11/status/mission_manager
      - /izzy/robot_description
      - /izzy/sensors/cameras/front/oak/detections/passthrough/camera_info
      - /izzy/sensors/cameras/front/oak/detections/passthrough/image_raw/throttled/compressed
      - /izzy/sensors/cameras/front/oak/detections/image_raw/throttled/compressed
      - /izzy/sensors/cameras/front/oak/segmentation/camera_info
      - /izzy/sensors/cameras/front/oak/segmentation/compressed
      - /izzy/sensors/cameras/front/detections
      - /izzy/sensors/cameras/front/usb/camera_info
      - /izzy/sensors/cameras/front/usb/image_raw/throttled/compressed
      - /izzy/sensors/deltat/grid
      - /izzy/sensors/deltat/soundings
      - /izzy/sensors/posmv/position
      - /izzy/sensors/posmv/orientation
      - /izzy/sensors/posmv/velocity
      - /izzy/tf
      - /izzy/tf_static
      - /izzy/udp_bridge/bridge_info
      - /izzy/udp_bridge/topic_statistics
      - /project11/platforms
      - /rosout
      - /tf
      - /tf_static
    storage:
      uri: /home/field/project11/logs/izzyboat
      max_bagfile_duration: 300

