/**/udp_bridge:
  ros__parameters:
    name: operator
    maximum_packet_size: 1000
    remotes_list:
      - izzy
    remotes:
      izzy:
        connections_list:
          - wifi
          - vpn
        connections:
          wifi:
            host: dora
            port: 4200
            return_host: salmon_ib
            return_port: 4200
            topics_list:
            - command
            - joystick_helm
            topics:
              command: {source: /izzy/project11/command}
              joystick_helm: {source: /izzy/piloting_mode/manual/helm}

          vpn:
            host: dora_v
            port: 4200
            return_host: salmon_v
            return_port: 4200
            topics_list:
            - command
            - joystick_helm
            topics:
              command: {source: /izzy/project11/command}
              joystick_helm: {source: /izzy/piloting_mode/manual/helm}
